package com.cougararray.TCPWebsocket;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.InetSocketAddress;
import java.net.ServerSocket;
import java.net.Socket;

import org.java_websocket.WebSocket;
import org.java_websocket.handshake.ClientHandshake;
import org.java_websocket.server.WebSocketServer;

import com.cougararray.OutputT.Output;
import com.cougararray.OutputT.Status;



//A lot of the information founded for using websockets can be founded here: https://www.geeksforgeeks.org/java-net-socket-class-in-java/
//ServerSocket is for SERVER side tasks (for receiving stuff)
//Socket is for CLIENT side tasks (for sending stuff)
public class WebsocketListener extends Thread{

    protected int port;
    private WebSocketServer server;

    public WebsocketListener(int port){
        this.port = port;
    }

    //extension of Thread
    public void run(){
        listen();
    }
    
    protected void listen(){
        Output.print("Starting WebSocket Receiver on port " + port, Status.GOOD);

        server = new WebSocketServer(new InetSocketAddress(port)) {
            @Override
            public void onMessage(WebSocket conn, String message) {
                Output.print("Received: " + message);
                conn.send("Message received: " + message);
            }


            //GENERATED BY org.java_websocket
            @Override
            public void onOpen(WebSocket conn, ClientHandshake handshake) {
                // TODO Auto-generated method stub
                throw new UnsupportedOperationException("Unimplemented method 'onOpen'");
            }

            @Override
            public void onClose(WebSocket conn, int code, String reason, boolean remote) {
                // TODO Auto-generated method stub
                throw new UnsupportedOperationException("Unimplemented method 'onClose'");
            }

            @Override
            public void onError(WebSocket conn, Exception ex) {
                // TODO Auto-generated method stub
                throw new UnsupportedOperationException("Unimplemented method 'onError'");
            }

            @Override
            public void onStart() {
                // TODO Auto-generated method stub
                return;
            }            
        };

        server.start();
        
    }


    //To test Websocket; you can write Websocket.java itself and see if it can send a message to itself.
    //Ideally, if you are to execute Main.java, this code is NOT executed. If you executed Websocket.java then this code is executed.
    //This is helpful for testing purposes.

    //@TODO!
    //Better Logging; I feel like to a new user, they have 0 idea what any of this is...
    //Better documentation
    public static void main(String args[]) {

        int port = 8000; // default test port

        WebsocketListener websocketListener = new WebsocketListener(port);
        websocketListener.start();

        WebsocketSenderClient.sendPing("localhost:8000");

    }
}
